### ISSUE TITLE
Conflict with PHP 7.1

### ISSUE THREAD

**Issue by jodzeee** [benjaminprojas/wp-editor#69]
When I changed to PHP 7.1, I got the following error on the plugins admin page:

`Warning: Illegal string offset 'deactivate' in /home/mysite/public_html/wp-content/plugins/wp-editor/classes/WPEditor.php on line 333

Warning: Illegal string offset 'edit' in /home/mysite/public_html/wp-content/plugins/wp-editor/classes/WPEditor.php on line 333

Warning: Illegal string offset 'deactivate' in /home/mysite/public_html/wp-content/plugins/wp-editor/classes/WPEditor.php on line 333

Warning: Illegal string offset 'edit' in /home/mysite/public_html/wp-content/plugins/wp-editor/classes/WPEditor.php on line 333

Fatal error: Uncaught Error: [] operator not supported for strings in /home/mysite/public_html/wp-content/plugins/ithemes-sync/lib/updater/admin.php:189 Stack trace: #0 /home/mysite/public_html/wp-includes/class-wp-hook.php(298): Ithemes_Updater_Admin->filter_plugin_action_links('<', 'backupbuddy/bac...', Array, 'all') #1 /home/mysite/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('<', Array) #2 /home/mysite/public_html/wp-admin/includes/class-wp-plugins-list-table.php(703): apply_filters('plugin_action_l...', Array, 'backupbuddy/bac...', Array, 'all') #3 /home/mysite/public_html/wp-admin/includes/class-wp-plugins-list-table.php(536): WP_Plugins_List_Table->single_row(Array) #4 /home/mysite/public_html/wp-admin/includes/class-wp-list-table.php(1213): WP_Plugins_List_Table->display_rows() #5 /home/mysite/public_html/wp-admin/includes/class-wp-list-table.php(1141): WP_List_Table->display_rows_or_placeholder() #6 /home/mysite/public_html/wp-admin/plugins.php(534): WP_List_Table->display() #7 in /home/mysite/public_html/wp-content/plugins/ithemes-sync/lib/updater/admin.php on line 189`

Note: I don't get the error on  PHP 7.0.14

With the advice of Gary Jones @Gamajo, I changed line 205 to:
`add_filter( 'plugin_action_links_wp-editor', array( $this, 'replace_plugin_edit_links' ), 9, 1 );'

And that fixed the error.

**Comment by benjaminprojas** [comment]
Thanks @jodzeee! I'll look into this as soon as I can.

**Comment by Spreeuw** [comment]
I think the actual fix here is setting $data properly as array [here](https://github.com/benjaminprojas/wp-editor/blob/master/classes/WPEditor.php#L324).
There's also a pull request already with this fix, #82 

Also see:
https://wordpress.org/support/topic/php-7-1-wp-4-73-plugins-listing-problem/#post-9303082

**Comment by presswizards** [comment]
@benjaminprojas Would you consider adding me to the WP Editor plugin repository using username "presswizards", and I could commit the PHP7.1 fix #82 needed by many that are affected as more and more people are switched (often suddenly) to PHP7.1+? 

I would consider doing simple maintenance of the plugin in the repository as well, and handling repository support threads.

Let me know your thoughts?
Rob

**Comment by FranzXKohl** [comment]
@benjaminprojas I ran into exactly this issue today with the latest WP version 5.2.3 after changing from PHP 5.6 to 7.3.9. I was able to fix the issue as described above by changing line 324 as described here: https://wordpress.org/support/topic/php-7-1-wp-4-73-plugins-listing-problem/#post-9303082

WP is using the Classic Editor plugin to re-enable the old WP Editor UI (customer does not like the new Gutenberg style of editing), and I refrained from deactivating your WP Editor plugin so far because I'm uncertain if that has any unwanted side-effects.

So I'm wondering why the issue with /wp-content/plugins/wp-editor/classes/WPEditor.php still hasn't been fixed for more than 2 years now - any idea?

Please let me know your thoughts.

Regards,
Franz
